import os
from PIL import Image 

from smolagents import CodeAgent, LiteLLMModel, GradioUI, DuckDuckGoSearchTool
from smolagents import Tool, tool
from utils.swarmui_flux_t2i import call_swarmui_api
from utils.download_image import get_image_from_url
from dowhen import when
import gradio.blocks

from dotenv import load_dotenv
load_dotenv()

@tool
def generate_image_with_flux1(prompt: str) -> str:
    """
    This tool generates an image based on a given text prompt using the flux1.dev model.

    Args:
        prompt: A descriptive natural language prompt that specifies the desired content and style of the image.
                For example: "A futuristic city skyline at sunset with flying cars".
    
    Returns:
        A URL string pointing to the generated image hosted on a server or storage service.
    """

    image_url = call_swarmui_api(prompt)
    return image_url

model = LiteLLMModel(
    model_id="deepseek/deepseek-chat",
    api_base="https://api.deepseek.com",
    api_key="sk-5bf6ebc4cb7d4e5f95843cf7f50a286a",
)

@tool
def download_image_from_url(url: str) -> Image.Image:
    """
    This tool downloads and returns an image from a given URL, typically the result of a text-to-image generation
    process using the flux1.dev model.

    Args:
        url: A direct URL pointing to an image file (e.g., PNG or JPEG), such as one generated by the flux1.dev model.
             The URL must be accessible via HTTP/HTTPS and should return raw image content.
    
    Returns:
        A PIL Image object representing the downloaded image.
    """
    img = get_image_from_url(url)
    return img

agent = CodeAgent(tools=[generate_image_with_flux1, 
                        download_image_from_url, 
                        # DuckDuckGoSearchTool(),
                        DuckDuckGoImageSearchTool(),
                        ], 
                  model=model)


# result = agent.run(
#     "扩充这段提示词，翻译成英文，并生成一张图片。一辆车停在山顶上"
# )
# print(result)   # Output: Gotham Catering Co.

# change the listen to localhost
# when(gradio.blocks, "2589").do("server_name='0.0.0.0'")

ui = GradioUI(agent)
ui.launch(share=False, server_name='0.0.0.0')

# when(GradioUI.launch, "408").do("server_name='0.0.0.0'")