[project]
name = "smolagent-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "gradio==5.36.1",
    "requests>=2.32.4",
    "smolagents[gradio,litellm,openai]>=1.19.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
